apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications                                # name of the application CR
  namespace: argocd                                         # namespace of the application CR
spec:
  destination:
    namespace: argocd                                       # namespace to deploy argocd-notifications resources
    server: https://kubernetes.default.svc                  # kubernetes cluster to deploy argocd-notifications resources
  project: default
  source:
    chart: argocd-notifications
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.7.0
    helm:
      values: |
        notifiers:                                           # Notifier defines the different notification-services to be used for routing notifications
          service.teams: |                                   # To use teams as notification service for ArgoCD sync notifications
            recipientUrls:
              General: $channel-teams-url              # $channel-teams-url is the webhook url passed from the secret
        secret:
          create: false
          name: msteams-webhook-url                          # Name of the secret created via sealed-secrets
        templates:                                           # Templates are used to generate the notification content
          template.app-sync-status-unknown: |                # template for sync-status="Unknown"
            teams:
              facts: |
                [{
                  "name": "Sync Status",
                  "value": "{{.app.status.sync.status}}"
                },
                {
                  "name": "Repository",
                  "value": "{{.app.spec.source.repoURL}}"
                }
                {{range $index, $c := .app.status.conditions}}
                  {{if not $index}},{{end}}
                  {{if $index}},{{end}}
                  {
                    "name": "{{$c.type}}",
                    "value": "{{$c.message}}"
                  }
                {{end}}
                ]
              potentialAction: |-
                [{
                  "@type":"OpenUri",
                  "name":"Open Application",
                  "targets":[{
                    "os":"default",
                    "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
                  }]
                },
                {
                  "@type":"OpenUri",
                  "name":"Open Repository",
                  "targets":[{
                    "os":"default",
                    "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
                  }]
                }]
              themeColor: '#FF0000'
              title: Application {{.app.metadata.name}} sync status is 'Unknown'
              text: Application {{.app.metadata.name}} has sync status as 'Unknown' at {{.app.status.operationState.finishedAt}}.
              summary: "{{.app.metadata.name}} has sync status as 'Unknown'"
          template.app-health-degraded: |                                    #Template for sync-status=health-degraded
            teams:
              facts: |
                [{
                  "name": "Health Status",
                  "value": "{{.app.status.health.status}}"
                },
                {
                  "name": "Repository",
                  "value": "{{.app.spec.source.repoURL}}"
                }
                {{range $index, $c := .app.status.conditions}}
                  {{if not $index}},{{end}}
                  {{if $index}},{{end}}
                  {
                    "name": "{{$c.type}}",
                    "value": "{{$c.message}}"
                  }
                {{end}}
                ]
              potentialAction: |
                [{
                  "@type":"OpenUri",
                  "name":"Open Application",
                  "targets":[{
                    "os":"default",
                    "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
                  }]
                },
                {
                  "@type":"OpenUri",
                  "name":"Open Repository",
                  "targets":[{
                    "os":"default",
                    "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
                  }]
                }]
              themeColor: '#FF0000'
              title: Application {{.app.metadata.name}} has degraded.
              text: Application {{.app.metadata.name}} has status as 'degraded' at {{.app.status.operationState.finishedAt}}.
              summary: "{{.app.metadata.name}} has status as 'degraded'"
          template.app-sync-failed: |                                      # Template for sync-status=failed
            teams:
              facts: |
                [{
                  "name": "Sync Status",
                  "value": "{{.app.status.sync.status}}"
                },
                {
                  "name": "Failed at",
                  "value": "{{.app.status.operationState.finishedAt}}"
                },
                {
                  "name": "Repository",
                  "value": "{{.app.spec.source.repoURL}}"
                }
                {{range $index, $c := .app.status.conditions}}
                  {{if not $index}},{{end}}
                  {{if $index}},{{end}}
                  {
                    "name": "{{$c.type}}",
                    "value": "{{$c.message}}"
                  }
                {{end}}
                ]
              potentialAction: |-
                [{
                  "@type":"OpenUri",
                  "name":"Open Operation",
                  "targets":[{
                    "os":"default",
                    "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
                  }]
                },
                {
                  "@type":"OpenUri",
                  "name":"Open Repository",
                  "targets":[{
                    "os":"default",
                    "uri":"{{.app.spec.source.repoURL | call .repo.RepoURLToHTTPS}}"
                  }]
                }]
              themeColor: '#FF0000'
              title: Failed to sync application {{.app.metadata.name}}.
              text: Application {{.app.metadata.name}} has sync failed at {{.app.status.operationState.finishedAt}}.
              summary: "{{.app.metadata.name}} has sync failed"
        triggers:                                                   # Triggers define the condition when the notification should be sent
          trigger.on-sync-status-unknown: |                         # Trigger for sync-status=unknown
            - description: Application status is 'Unknown'
              oncePer: app.metadata.name
              send:
              - app-sync-status-unknown
              when: app.status.sync.status == 'Unknown'
          trigger.on-health-degraded: |                             # Trigger for sync-status=health-degraded
            - description: Application has degraded
              oncePer: app.metadata.name
              send:
              - app-health-degraded
              when: app.status.health.status == 'Degraded'
          trigger.on-sync-failed: |                                 # Trigger for sync-status=failed
            - description: Application syncing has failed
              oncePer: app.metadata.name
              send:
              - app-sync-failed
              when: app.status.operationState.phase in ['Error', 'Failed']
        subscriptions:                                             # Subscription defines which notifier to be used based on the triggers
          - recipients:
              - teams:General                                # To use MS Teams channel as the notifier
            triggers:
              - on-sync-status-unknown
              - on-health-degraded
              - on-sync-failed
        metrics:                                                   
          enabled: true                                            # To enable prometheus metrics
          serviceMonitor: 
            enabled: true                                          # To enable service-monitor
            additionalLabels:
              release: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true